### ISSUE TITLE
Mistyping repeating keys

### ISSUE THREAD

**Issue by ErtugKaya** [Zhouzi/TheaterJS#10]
People won't mistype repeated keys. For instance, when you are typing `...` it is very unlikely for someone to mistype 2nd or 3rd dot. So maybe you should check if previous character is same as current one and don't mistype if so.

What do you think?

**Comment by Zhouzi** [comment]
You are absolutely right @ErtugKaya. I think that some people, the least experienced ones (e.g. with `.1` experience), can make mistakes even on repeated characters. So it might be interesting that there's little chances to actor with experience between `0` and `.3` to make this kind of mistakes. 

Thank you for the suggestion, I'll work on it!

**Comment by Zhouzi** [comment]
This is now included: https://github.com/Zhouzi/TheaterJS/commit/25688c4887bb1e97c62ca2be092207915bc08906

Unless an actor has `.3` or less experience, he has no chances to make a mistake.

**Comment by ErtugKaya** [comment]
Nice touch. Congratulations for your 1k+ stars project.

**Comment by Zhouzi** [comment]
Thank you! :)
