### ISSUE TITLE
Homepage link is broken

### ISSUE THREAD

**Issue by kloplop321** [Zhouzi/TheaterJS#11]
> The demo is also available on the TheaterJS page.

in README.md links to a dead page. 

> Not Found
> 
> The requested URL /TheaterJS was not found on this server.

**Comment by Zhouzi** [comment]
Hello @kloplop321 and thank you for the report! I thought the issue was fixed but I'll make some more investigations. Did you ever accessed to the demo page or you always faced a 404 page?

**Comment by kloplop321** [comment]
Just click on the link from the readme, which goes to http://gabinaureche.com/TheaterJS

The codepen loads for me, but unfortunately does not seem to function.
Chrome Version 39.0.2171.95 m

So, I don't get to see the awesome darth vader scene.

**Comment by Zhouzi** [comment]
Actually I never faced a 404 page myself but several users reported it. From my side the link works perfectly. I started to monitor the site to figure out what's happening.

For now, I included the sources back in the codepen: http://codepen.io/Zhouzi/pen/JoRazP
You should be able to access the darth vader scene now hehe :)

Thank you and sorry for the inconvenience!

**Comment by Zhouzi** [comment]
Hello @kloplop321

I made some fixes in the dns configuration. Could you please try again to access http://gabinaureche.com/TheaterJS and see what happens? It'd be much appreciated.

**Comment by kloplop321** [comment]
Sorry about not getting back to you, yes, it is fixed now! :smile_cat:

**Comment by Zhouzi** [comment]
No problem @kloplop321, thank you! :+1:
