### ISSUE TITLE
Publishing the project to Bower 

### ISSUE THREAD

**Issue by Stephn-R** [Zhouzi/TheaterJS#14]
Hey, I think it would be a great idea to publish this project as a new Bower Component after a license is chosen. 

http://bower.io/docs/creating-packages/

**Comment by Zhouzi** [comment]
Thanks for the suggestion @Stephn-R.
I am not an user of bower my self but I'll have a look and see how I can make it available as a bower component.

**Comment by Stephn-R** [comment]
Not a problem, I can help with the transitioning for this project in a bower component
