### ISSUE TITLE
Add mistakes including incorrect capitalizations and typing characters ahead and then erasing

### ISSUE THREAD

**Issue by augbog** [Zhouzi/TheaterJS#16]
I think it would be awesome if we could improve the realism of mistakes made by making it so that capital letters are sometimes confused or users go back to fix a capital letter. 

i.e. And then the fox ran. so... --> And then the fox ran. So...

Also mistakes where users type the next letter in the word (sometimes this happens because they didn't push the key with one of their fingers hard enough).

i.e. And then the fx... --> And then the fox...

Regardless, really cool library.

**Comment by Zhouzi** [comment]
Thank you for the suggestion @augbog! It makes sense, I've added it to the todos: https://github.com/Zhouzi/TheaterJS/blob/gh-pages/README.md#todo

Feel free to contribute if you will :)
