### ISSUE TITLE
Decompose "Experience" into "Speed" and "Accuracy"

### ISSUE THREAD

**Issue by williamg** [Zhouzi/TheaterJS#18]
Right now the "experience" factor increases speed while decreasing mistakes. I don't think this is totally accurate. I think, optimally, "experience" should be decomposed into "speed" and "accuracy" rather than just one parameter like it is now. This would allow you to have speed demons that make lots of mistakes or slow, deliberate typists that are almost flawless.

**Comment by Zhouzi** [comment]
Thank you for the suggestion @williamg, this is a great idea! I've added it to the todos: https://github.com/Zhouzi/TheaterJS/blob/gh-pages/README.md#todo

**Comment by Zhouzi** [comment]
This is now implemented as of https://github.com/Zhouzi/TheaterJS/commit/7ae832f58f6aa818551ae5a8a58c401d74081b45
