### ISSUE TITLE
How can I stop writing?

### ISSUE THREAD

**Issue by pagoad** [Zhouzi/TheaterJS#29]
I write on page scrolling.
I need to stop writing when user see some element.
How can i stop writing even if actor write only half of sentence.

**Comment by Zhouzi** [comment]
Hello @pagoad!

For now, TheaterJS doesn't provide neither a `stop` or `pause` method. It'd be probably interesting to think about implementing it.

What's your real need? You want to "pause" the animation, even half of sentence, and then be able to play from where it left? Or would you start from scratch again? Maybe just call "play" and type the whole sentence again?

**Comment by pagoad** [comment]
When I scrol page i want to write in header some sentences.
Every section has his own.
When I scroll fast "Actor" has no chance to write sentence before next section will start.
And it is look strange when you are on bottom of page and you see he is writing  unaccomplished sentences one after the other

**Comment by Zhouzi** [comment]
Thank you for the details @pagoad, I'm thinking about implementing such feature in TheaterJS. Do you have a link to your site so I'd have a look?

**Comment by pagoad** [comment]
I'm coding this website right now, I have it only on localhost.
When i finish i will show you :)
When could you implement this feature? How much time? :)
Thx!

**Comment by Zhouzi** [comment]
Hello @pagoad, the `stop` method is now implemented. Have a look at [the documentation](https://github.com/Zhouzi/TheaterJS/wiki/2.-API-Reference#stop). Let me know when your project is available online :)

**Comment by pagoad** [comment]
Thx! :D

**Comment by Zhouzi** [comment]
You are welcome! ;)

**Comment by pagoad** [comment]
It does not work :(
If I stop it, i cant resume with new text. 

     headerTheater.stop();
     headerTheater.play();
     headerTheater.write('Header:' + h2, 100);

Nothing is happen.

**Comment by Zhouzi** [comment]
I am not sure to understand what you are trying to do, could you please post the whole code relevant to your usage of TheaterJS?

Also, note that the `write` method implicitly calls `play` (unless you have set `autoplay` to `false`). So:

```javascript
headerTheater.stop();
headerTheater.write("Header:" + h2, 100);
```

Should be enough.

**Comment by pagoad** [comment]
For example:
   
    $(window).on('scroll', function() {
        $('section:in-viewport(200)').each(function() {
                var h2 = $(this).data('h2');
                headerTheater.stop();
                headerTheater.write('Header:' + h2, 100);
        }
    });

It doesnt work. Without .stop() it's work, but when I use this function text dont want to show.

**Comment by Zhouzi** [comment]
Reopening as the `play` and `stop` methods are not working properly together.

**Comment by Zhouzi** [comment]
The `play` method should now work as expected. Have a look at this [fiddle](http://jsfiddle.net/to1puqam/1/), it will probably help you deal with your case. Let me know if you have any questions ;)
