### ISSUE TITLE
CDN ?

### ISSUE THREAD

**Issue by marvinroger** [Zhouzi/TheaterJS#31]
Hi!

Would you mind if TheatherJS was hosted on a CDN like [cdnjs](https://cdnjs.com/) or [jsDelivr](http://www.jsdelivr.com/) ? It would be great as this would allows us to use the lib without actually serving it from our own servers.

**Comment by Zhouzi** [comment]
Hello @marvinroger and thank you for the suggestion. TheaterJS is now pending review to be added to jsDeliver: https://github.com/jsdelivr/jsdelivr/pull/3564

**Comment by marvinroger** [comment]
Great news! Thanks for the quick response.

**Comment by Zhouzi** [comment]
TheaterJS is now available on jsDeliver: `//cdn.jsdelivr.net/theaterjs/latest/theater.min.js`

[Documentation on usage](https://github.com/Zhouzi/TheaterJS/wiki) has also been updated.
