### ISSUE TITLE
How to use with node/npm/browserify/webpack ?

### ISSUE THREAD

**Issue by vkbansal** [Zhouzi/TheaterJS#33]
How to use with node/npm/browserify/webpack ?

**Comment by Zhouzi** [comment]
Hello @vkbansal,

for now TheaterJS can't be used in the environments you mentioned but I am working on it and will keep you updated. Do you plan to use TheaterJS on the server side? I would be curious about it :)

**Comment by vkbansal** [comment]
I'm was looking to use it with browserify

**Comment by Zhouzi** [comment]
Hello @vkbansal,

you should now be able to use TheaterJS with browserify ;)

**Comment by vkbansal** [comment]
Have you published to npm?

I tried searching but could find it

**Comment by szarouski** [comment]
Hi @Zhouzi, I'll be using TheaterJS in combination with http://tholman.com/dom-animator/ to make an Easter egg for my colleagues :) Is it possible to subscribe to each actor and to observe them typing? Currently there is `:start` and `:end`, while I need something like `:edit` event which contains current phrase.

**Comment by Zhouzi** [comment]
Hey @szarouski! Actually, making TheaterJS work with dom animator (really cool by the way!) would be really hard as it uses "frames". That been said, you might not need it to reproduce a similar effect. Have a look at this fiddle: http://jsfiddle.net/avbb6wcw/

**Comment by szarouski** [comment]
Nice, thank you :)
