### ISSUE TITLE
Is there a way to control the ERASE speed?

### ISSUE THREAD

**Issue by orcfull** [Zhouzi/TheaterJS#34]
Hey dude,

Love this but I'm wondering if there is a way to set a parameter to control the erasing speed?

Something similar to this.
                    .describe("reader", { speed: 15, accuracy: 1, invincibility: 4, erase:25 }, "#reader")

Thanks for the awesome plugin.

**Comment by Zhouzi** [comment]
Hello @orcfull,

glad you like TheaterJS :)

The `erase` speed is based on actor's `speed`, with an increment of `.2`. It means that actors actually erase faster than they "type".

What are you trying to achieve? You'd like to configure erasing and typing speed independently?

Oh and note that `speed` is supposed to be an integer between `0` and `1` ;)

**Comment by orcfull** [comment]
Hey @Zhouzi 

I low how realistic it feels, I've been adding in soundbites for typing and it has a really human feel. Thanks for all your hard work. 

What I'm trying to achieve is a human-like speed of typing out followed by either an instant delete of the typed content or a very fast delete. Almost an instant delete if you get me?

Yes, personally I'd love to be able to alter those independently. Any advice on maybe play around with the code myself to achieve that?

Cheers for the the doc link, apologies for not reading through it thoroughly enough, just been playing around with everything:)

**Comment by Zhouzi** [comment]
My pleasure! :)

You can configure TheaterJS to "instant erase" speeches: `new TheaterJS({ erase: false })`.

That been said, I'll probably publish a new release at the end of the week to make the increment filter on `erase` scenes configurable. If you are in a hurry, have a look at https://github.com/Zhouzi/TheaterJS/blob/gh-pages/src/theater.js#L526

Update `.2` to whatever value fits your needs (the greater, the faster). This filter actually increases the calculated speed (which is based on several criteria).

**Comment by Zhouzi** [comment]
Hello @orcfull,

`erase` scenes now accepts a second argument that allows you to configure the animation speed. I've updated the [documentation](https://github.com/Zhouzi/TheaterJS/wiki/2.-API-Reference#-1-erase-x-characters) ;)

**Comment by orcfull** [comment]
Great @Zhouzi, really fantastic work and thanks for being so open about it all. 

Excited to see how this develops with time:)

**Comment by Zhouzi** [comment]
Thank you for your kind support @orcfull :)
