### ISSUE TITLE
Issue with html when appending speech

### ISSUE THREAD

**Issue by Zhouzi** [Zhouzi/TheaterJS#37]
http://jsfiddle.net/v7gdmc4a/

**Comment by afaqurk** [comment]
:+1: 
I noticed the same thing when implementing TheaterJS for my blog. Line breaks, for some reason, render before the current line and not at the designated position.

**Comment by Zhouzi** [comment]
Thanks for confirming this issue @afaqurk, I plan to release a fix soon ;)

**Comment by farhadyousefi** [comment]
than you for this amazing js. but please check theater.js to work fine with jshint. :)

**Comment by Zhouzi** [comment]
Thanks @farhadyousefi ;) I am currently rewriting TheaterJS in ES6 and looking into [standard](http://standardjs.com/), not exactly jshint but I guess it'd do the work too.

**Comment by Zhouzi** [comment]
@afaqurk @farhadyousefi  this issue is now fixed thanks to v2, here is a working jsFiddle: http://jsfiddle.net/v7gdmc4a/1/

I also added [standard](http://standardjs.com/) to the workflow ;) If you're interested in migrating from v1 to v2, have a look at the [guide](https://github.com/Zhouzi/TheaterJS/blob/master/MIGRATING.md) and let me know if you're having any trouble.
