### ISSUE TITLE
Infinite Loops

### ISSUE THREAD

**Issue by siscia** [Zhouzi/TheaterJS#38]
Hi,

I am trying to run theater inside an infinite loop where I create the random text to show.

However I had the impresion that Theater is blocking the execution.

Is that possible ?

**Comment by Zhouzi** [comment]
Hey @siscia,

That's an interesting use case and you shouldn't have too much trouble to make it work with TheaterJS. The only thing to keep in mind as that you need to wait for the animation to be finished before calling for the next one. I'd recommend to go with a recursive function:

```html
<div id="droid"></div>

<script>
  var theater = new TheaterJS();
  theater.describe('droid', .8, '#droid');

  var i = 1;
  (function loop () {
    theater
      .write('droid:Hi, I am C' + (i++) + '-PO')
      .write(loop)
    ;
  })();
</script>
```

[jsFiddle](http://jsfiddle.net/fa16kcaL/1/)

Let me know if it do fulfill your requirements ;)

**Comment by siscia** [comment]
That is really nice, thank you :)
