### ISSUE TITLE
Script File Throwing Error on Line 85

### ISSUE THREAD

**Issue by andandandandrew** [Zhouzi/TheaterJS#39]
Hi there,

AWESOME STUFF first of all.

So in codepen, everything is working just great (http://codepen.io/andandandandrew/pen/XmKEMK). I'm importing the theater.js file then typing the plugin scripty part in the JS panel, which is tantamount to an inline script if I'm correct.

So where I'm trying to use this on a site I'm working on, I have the theater.js script dynamically loading using PHP (it's only used on one page) loading using src="" after the footer, immediately followed by another inline script with the following code in it, which is also php'd in as an inline script:

<script type="text/javascript">(function () {
  "use strict";
  var theater = new TheaterJS();
  theater.describe("typeit", { speed: 0.85, accuracy: 1, invincibility: 6 }, "#typeit");
  theater

    .write("typeit:What's up my homies?!?", 1000)
    .write("typeit:It's typing itself. OMG!!!", 800)
    .write("typeit:CAN YOU BELIEVE IT?", 1600)
    .write("typeit:We can change the length each message stays too. This one is ten seconds.", 10000)
    .write("typeit:This is one second.", 1000)
    .write("typeit:Andrew is super neat.", 1000)

    .write(function () { theater.play(true); });
})();</script>

I am getting a console error (screenshot attached) on line 85 of the script file: Uncaught TypeError: Cannot set property 'innerHTML' of null

![screen shot 2015-09-28 at 2 13 17 pm](https://cloud.githubusercontent.com/assets/6225112/10144453/c1ac8fb0-65eb-11e5-8121-e5561f93c317.png)

Any idea what's going on here? It's being used on the homepage of a WordPress Site and is not typing anything, even though the markup is the same as in the pen (id to JS it is anyways). This is where it should be typing, but it's not:

<img width="1477" alt="screen shot 2015-09-28 at 2 24 10 pm" src="https://cloud.githubusercontent.com/assets/6225112/10144651/b5c8b240-65ec-11e5-9277-acf3cfaeaced.png">

Any ideas? Is it the PHP loading that's doing it? I've copied the script exactly from the repo—there's not something in the actual script file I need to update, right?

Thanks for the help.

**Comment by Zhouzi** [comment]
Thanks @andandandandrew, glad you like it ;)

As it stands, it looks like it's trying to set the `innerHTML` of a null variable - which means that the DOM element couldn't be found. There are two possible causes:

1. TheaterJS tries to access the DOM element before the DOM is ready.
  * To fix this issue, you can whether wrap the code in a "DOM ready" listener: `document.addEventListener('DOMContentLoaded', function() { /* the code goes here */ }, false);` or put your scripts at the end of the `<body>` tag.
2. There are no element matching the actor's selector.
  * Make sure that the selector passed as the actor's "voice" is correct, e.g `theater.describe('actorName', {/* props */}, '#some-selector')`. You can check this by opening your browser's console and execute `document.querySelector('#some-selector')`.

Let me know if that do help :)

**Comment by andandandandrew** [comment]
OK, so I am a super JS idiot, so please bare with me. I added the DOM ready listener to theater.js by prepending "document.addEventListener('DOMContentLoaded', function() {" before the start of the file's code, and appended "}, false);" after the last line in theater.js.

That solved the inner HTML null issue. But now, I have another issue.

Now I'm getting this message: Uncaught ReferenceError: TheaterJS is not defined in the console.

Here's a screenshot that proves the actor and correct selector are being used. Any thoughts? Did I do it wrong. There's a very good chance I did.

![screen shot 2015-09-28 at 4 43 39 pm](https://cloud.githubusercontent.com/assets/6225112/10148473/b6d8ab6c-6601-11e5-9671-309243c1b1ac.png)

Thanks for your help my developer brother in arms; you are a rockstar!

**Comment by Zhouzi** [comment]
Actually the "DOM ready listener" should wrap the code that is actually manipulating the DOM: your code (but not the TheaterJS library).

That been said, I can see that the scripts are already placed at the end of the `<body>` so you shouldn't have to add the listener. Give it a try anyway and if that still does not solve your issue, my next bet is that the html content is loaded at a later time.

Any chance I could access to a version of this page? If not, try the following: when you're on the page, in your browser, use the browser's functionality to look at the source code (not from the inspector). Make sure you can find the `<span id="typeit" />` in there.

**Comment by andandandandrew** [comment]
I'll recreate the page on my personal site tonight and send you the link. It will still function the exact same way that this one is supposed to. Thanks for all the help, it's awesome!

**Comment by andandandandrew** [comment]
Hi there. I just downloaded the webpage and threw it up on my personal site's server. Pleases excuse the trash that is the markup in there. I really appreciate you taking a look at the code.

http://and-rew.com/lift

**Comment by Zhouzi** [comment]
I couldn't load the page correctly but looking at the source code, I found that the span's id is `typeit lift-is` which is not matched by the `#typeit` selector.

<img width="378" alt="screen shot 2015-09-30 at 20 22 40" src="https://cloud.githubusercontent.com/assets/2291025/10202415/0cf621ea-67b1-11e5-872e-04f841d5144e.png">

Looks like a mistake since an element can't have two ids and spaces are not allowed within an id name. So to get it right you'll have to: remove the "addEventListener" code from theater-min.js and use a proper id. Give it a try and let me know ;)

**Comment by andandandandrew** [comment]
IT WORKS!!! Thanks so so so much. I think what it was is that I had 2 IDs in the inline script part, why? I HAVE NO IDEA! I feel dumb, but am literally dancing around about it now!

**Comment by Zhouzi** [comment]
haha really glad to help and thanks for being so enthusiastic :)
