### ISSUE TITLE
Ability to have text fade instead of untype

### ISSUE THREAD

**Issue by andandandandrew** [Zhouzi/TheaterJS#40]
Is there a way that this plugin can be used to fade the type after it's been typed in as opposed to the delete key function that's currently in there?

**Comment by Zhouzi** [comment]
That's a nice idea! What you have to do is:

1. Turn off the "erase" animations
2. Add "async" scenes that fade out the element and then play the next scene

Have a look at this fiddle: http://jsfiddle.net/bLn88v0s/

**Comment by andandandandrew** [comment]
You're my favorite GitHubber! Thanks!

**Comment by Zhouzi** [comment]
Glad to help! :)

**Comment by AmineIzumi** [comment]
Hi ! Sorry to bump this, but since now there isn't anymore theater.next() and theater.write() and maaaany more, how could I achieve that ?

**Comment by Zhouzi** [comment]
The idea remains the same, the only change is that TheaterJS doesn't make any assumptions about whether the callback is synchronous or not. So a callback scene receives a `done()` function as first argument, which is the equivalent of the old `theater.next()`. Here is what it looks like with the latest version: https://jsfiddle.net/dc5e2s5r/1/

That been said, there are two things that I'm not really happy with:

1. Having to add the fadeOut callback after each scenes
2. The fact that disabling `erase` doesn't clear out the display value

I'll work on that to make it simpler but until then, the fiddle shows a decent solution.

**Comment by AmineIzumi** [comment]
Having to add the fadeout isn't really a problem now, since you've implemented 'scene:end' event ^^
Thanks for the tip !

**Comment by Zhouzi** [comment]
Yes, the thing is that the events are non-blocking so you can't delay the execution of the next scene: #53

**Comment by AmineIzumi** [comment]
Yep, I saw the issues you opened, you literally predicted my questions haha :)
A workaround i'm using is too set some delay at the beginning of a new scene. Like that : .addscene(400,'luke: Heeey ')

**Comment by Zhouzi** [comment]
With next release it should be either to handle such case:

```javascript
var theater = theaterJS({ erase: false })

theater
  .on('type:end', fadeOut)
  .addActor('vader')
  .addScene('vader:Luke.', 'vader:I am your father.', theater.replay)

function fadeOut () {
  theater.stop()

  var $element = $(theater.getCurrentActor().$element)

  $element.fadeOut(500, function () {
    theater.getCurrentActor().displayValue = ''
    $element.show()
    theater.play()
  })
}
```
