### ISSUE TITLE
Script freezing (randomly) during multiple typed phrases

### ISSUE THREAD

**Issue by andandandandrew** [Zhouzi/TheaterJS#41]
On my agency's homepage, we are making good use of theater.js. My boss has trouble with it freezing mid sentence on his computer (year and a half old macbook air). I know it's hard to replicate without his actual machine, but view it here and see if the same happens with you. Maybe you can throttle your bandwidth of memory in dev tools to recreate?

http://lift1428.com

Thanks bud!

**Comment by Zhouzi** [comment]
Glad to see you're having fun with TheaterJS :)

Is his browser completely freezing or everything's working as usual but the typing animation? What browser/version is he using?

The latest version of TheaterJS could help fixing the issue but there are lots of breaking changes. I'll publish a simple guide on how to migrate from v1.x to v2 by the end of the week if that seems interesting to you.

**Comment by andandandandrew** [comment]
Everything is working, just some of the typing stops mid sentence. Not sure why.

He's using Safari 8.x, not sure exactly what release. He's gone for the day so I'll get the actual version tomorrow.

A guide on migrating to v2 would be AMAZING! Thanks friend!

**Comment by Zhouzi** [comment]
Here you go: [Migrating from v1 to v2](https://github.com/Zhouzi/TheaterJS/blob/master/MIGRATING.md)

Let me know if you're having trouble and if you're still facing the freezing issue.

**Comment by Zhouzi** [comment]
Could you give a try to v2 @andandandandrew?

**Comment by andandandandrew** [comment]
Yes! I will try v2 today or tomorrow and get back to you. Thanks a ton!

**Comment by Zhouzi** [comment]
Any news about this issue @andandandandrew? Feel free to reach me on gitter if that's easier: https://gitter.im/Zhouzi/TheaterJS

**Comment by andandandandrew** [comment]
Today is do a bunch of bug fixing day, so I'll get the new script in there and report back! Thanks!

**Comment by Zhouzi** [comment]
Hope you could fix it, I'm closing but let me know if you're still having trouble ;)

**Comment by andandandandrew** [comment]
Sorry for not updating! It's all good now. It was partly an old old version of Safari being used. I updated to v2 on the dev server it it's working swimmingly! Thanks so much!

**Comment by Zhouzi** [comment]
No problem, glad everything's working just right ;)
