### ISSUE TITLE
Bower main file could not be found in release

### ISSUE THREAD

**Issue by timwangdev** [Zhouzi/TheaterJS#42]
`"main": "build/theater.js",` in `bower.json` could not be found in release and repository.

It would cause some error when use `gulp` tools.

**Comment by Zhouzi** [comment]
Thanks for pointing that out @timwangdev

**Comment by timwangdev** [comment]
@Zhouzi You might also want to add uncompressed `theater.js` to `bower.json` main file, according to [bower.json spec](https://github.com/bower/spec/blob/master/json.md#main) recommendation.

**Comment by Zhouzi** [comment]
Thanks @timwangdev, I went through the spec and updated a few things in the `bower.json` file.
