### ISSUE TITLE
Erasing a sentence/word faster

### ISSUE THREAD

**Issue by merqurio** [Zhouzi/TheaterJS#46]
Hi there,

We love using your script at our [page](http://iomed.es), and we wanted to use it even more. I've been looking to the docs, looking for a faster way of erasing a sentence but I didn't found any API. Should I write my own custom callback ?

Thanks a lot !!

**Comment by Zhouzi** [comment]
Hey @merqurio, glad to see that you are using TheaterJS :)

So you are looking for a way to erase a sentence faster while not modifying the configuration's min/max speed, right? If that's what you're looking for, sadly there's no way to do it yet. It'd be a great feature so I'll work on it and keep you updated ;)

**Comment by merqurio** [comment]
Thanks ! I tried passing a fn that modified the element, but didn't work..
```javascript
.addScene(function(done){
    document.querySelector(".x").innerText = "";
    done();
})
```

**Comment by Zhouzi** [comment]
Oh my bad, I thought you wanted to keep the animation but increase its speed. What you are looking for is to clear the actor's display value. Actually, an actor is an object that has a displayValue property and theaterJS relies on it to set the element's innerHTML. This is why your callback didn't seem to work. Here is the way to go:

```javascript
const theater = theaterJS()

theater
  .addActor('typer')
  .addScene('typer:Hey there!', 400)
  .addScene('typer:How u doing?', 400)
  .addScene(function (done) {
    theater.getCurrentActor().displayValue = ''
    done()
  })
  .addScene('typer:Nice to meet u!', 400)
  .addScene(theater.replay)
```

And here is a jsFiddle to see it in action: https://jsfiddle.net/086t2mew/

**Comment by merqurio** [comment]
Great !!!! Thank you very much !!

I just tested it and works perfectly, but maybe you were right and changing the speed would be more natural ? dunno. peace :v:

**Comment by Zhouzi** [comment]
Well, I guess it depends but let me know if you finally prefer to keep the animation ;)

Anyway, have fun :)

**Comment by merqurio** [comment]
In the end I just left the animation. I'll try to dive into the code the next week and see if I can implement a way of accelerating the animation in particular cases and do a PR. :+1: thanks for support !
