### ISSUE TITLE
Examples are not working out of the box (ES6 syntax)

### ISSUE THREAD

**Issue by nishantdeveloper** [Zhouzi/TheaterJS#47]
I configured the javascript and all. It is easily working in Firefox. But in chrome it is not starting. Please help me

**Comment by nishantdeveloper** [comment]
Ok! i found out the problem. I copied the code that is given in the example and where the first line is 
`let theater = theaterJS()`

When i changed it to:
`var theater = theaterJS()`
It started working.

**Comment by Zhouzi** [comment]
Hey @nishantdeveloper! Yep, `let` is an ES6 keyword that's not yet supported across all browsers. I should probably update the examples to use pure ES5 to avoid any confusion. I'll keep this issue open until I do so.

In the meantime, feel free to get in touch if you're facing any other issue ;)

**Comment by Zhouzi** [comment]
The examples finally use plain ES5 syntax ;)
