### ISSUE TITLE
Global option to slow down erase scenes without affecting type's speed

### ISSUE THREAD

**Issue by AmineIzumi** [Zhouzi/TheaterJS#48]
When the typing speed is set to fast, the erasing seems really slow compared to typing. Is it actually possible to change the erasing speed ?
[Closed because it was a duplicate, and as i read you're already working on it o/ ]

**Comment by Zhouzi** [comment]
Hey there! Sorry for being late. If you're still having trouble configuring the erase scene's speed, here is a fiddle that illustrates how you could do that: https://jsfiddle.net/yexw3do1/

erase scenes accept an argument that's used as the delay between each erased characters. To add a scene with an argument you'll need to provide a scene object, e.g:

```javascript
var theater = theaterJS()

theater
  .addScene('luke:Hey there!')
  .addScene({ name: 'erase', args: [10] })
```

Have a look at the fiddle for a working demo ;)

**Comment by AmineIzumi** [comment]
Oh, it's perfect ! Thank you so much !
However i don't understand how to use it correctly, and your fiddle only shows the case of erasing the last sentence.
Actually, I'd like to implement that in a dialog. Here's a concrete example of what i'm trying to achieve :
`
  .addScene('luke:Hey there!')
  .addScene('vader:Hi.')
  .addScene({ name: 'erase', args: [10] }) //To erase Luke's sentence before writing a new one
  .addScene('luke:Who are you?')
` 
Thank you for your time !

**Comment by Zhouzi** [comment]
In fact erasing and typing speeds are calculated in the same way and depends on two things:

* the options' minSpeed and maxSpeed
* the actor's speed characteristic

So for now, you can't affect the erase's speed without affecting the type's speed too. Unless, of course, you're creating an erase scene each time you need it:

```javascript
.addScene('luke:Hey there!')
.addScene('vader:Hi.')
.addScene({ name: 'erase', args: [10] })
.addScene('luke:Who are you?')
.addScene({ name: 'erase', args: [10] })
```

That been said, I can see the use case and it could be a great feature so I'm reopening the issue and I'll see when I can come up with something :)

**Comment by AmineIzumi** [comment]
Okay, thanks once again for your help !

**Comment by Zhouzi** [comment]
I've implemented a way to configure type and erase speed independently, have a look at the [documentation](https://github.com/Zhouzi/TheaterJS#documentation) :) I'm about to release a new version to npm/github/bower.

**Comment by AmineIzumi** [comment]
So, the erase speed will be affected by max/min scene erase speed, and actor speed, and is not specific to an actor's option (like 'erase', in the minimalist version you shown in the other post), right ? Awesome, i'm going to play with this option right now ! Thank you so much for your time and kindness !
By the way i noticed a small typo in the documentation, here it is : 

> ` "maxSpeed": {`
> `    "erase": 450,`
> `    "type": 450`
> `  }`
> `}`
> 
> Is equivalent to:
> 
> `{`
> `  "minSpeed": 80,`
> `  "maxSpeed": 80`
> `}` 

(sorry, i don't know how to insert line breaks in GitHub code view :c )
If I understood correctly, it should be "maxSpeed": 450, isn't it ?

**Comment by Zhouzi** [comment]
Yes that's it, the configuration is global and not really related to an actor. You should be able to have the desired result by tweaking the erase/type and actor's speed. I'll make some tests and see if adding a greater bonus to the erase speed would make sense.

Thank you very much regarding the documentation, you are absolutely right :)
