### ISSUE TITLE
TheaterJS halts with blinking text cursor

### ISSUE THREAD

**Issue by ErtugKaya** [Zhouzi/TheaterJS#5]
In your example, I get random "Uncaught TypeError: Cannot read property '0' of undefined" at line 152. This causes text cursor blink at the end of a word and cannot complete it's job.

I believe p in ```p = chars[c];``` is undefined.

I think it happens when your code is mis-typing a space character.

Correction: It happens after space, before first letter of a word.

Using latest chrome and Win 7.

Kind regards and keep up the good work.
Ertug

**Comment by Stephn-R** [comment]
Well this brings up a good question, why would you have to perform this check if the for loop only loops through existing components?

```js
for (c in chars) {
    if (!chars.hasOwnProperty(c)) continue;

    p = chars[c];

    if (Math.abs(charPosition[0] - p[0]) <= threshold &&
        Math.abs(charPosition[1] - p[1]) <= threshold) {
            nearbyChars.push(c);
        }
    }
```

**Comment by Zhouzi** [comment]
Thank you for pointing it out @ErtugKaya!

You are absolutely right. Actually, the error was thrown when the mistaking character wasn't found in the available characters list. I fixed it so it simply returns a random character in this case.

@Stephn-R Are you talking about `if (!chars.hasOwnProperty(c)) continue;`?
This test avoids looping through potential prototyped properties. For example:

```javascript
Object.prototype.foo = "foo";

var bar = { bar: "bar" };

// logs "bar", "foo"
for (var k in bar) console.log(k);

// logs "bar"
for (var k in bar) {
  if (!bar.hasOwnProperty(k)) continue;
  console.log(k);
}
```

**Comment by Stephn-R** [comment]
@Zhouzi This makes sense!!! I am glad you pointed that out for me :) thanks

**Comment by Zhouzi** [comment]
@Stephn-R No problem dude! :)

**Comment by ErtugKaya** [comment]
You are welcome @Zhouzi . Keep up the good work.
