### ISSUE TITLE
[enhancement] fire an event when a scene is finished

### ISSUE THREAD

**Issue by AmineIzumi** [Zhouzi/TheaterJS#51]
Hi ! I'm working with the events .on('type:start, erase:start') or type:end erase:end to make the text container duplicate itself when someone finished typing. However, i added many 'long scenes', like this : 
```
    .addScene('vader:Luke...', 400)
    .addScene('luke:What?', 400)
    .addScene('vader:I am', 200, '.', 200, '.', 200, '. ')
    .addScene('Your father!')
    .addScene('luke: ...',400,'Whaat the',700,-3,'are you saying!?')
    .addScene(800)
```
 [Fiddle showing the (in)usability of type:start](https://jsfiddle.net/AmineIzumi/u1ojxkfc/)

so the 'type:end' event doesn't fit my needs anymore, since it's triggered multiple times in one 'sentence' .

I know that adding a function scene after the one i want to duplicate would probably work, but in a long scenario I then have to copy that function scene after every scene, which isn't really convenient. Could it be possible to add an event "scene: start" and "scene : stop" ?

**Comment by Zhouzi** [comment]
That makes total sense and I can see how useful it could be. So here you go: there's now a `sequence:start` event emitted when a sequence starts and `sequence:end` when it ends as of 2.1.0.

**Comment by AmineIzumi** [comment]
Thank you so much, once again !

**Comment by Zhouzi** [comment]
That should be pretty easy to implement and once again, makes sense so I'll open an issue regarding this feature.
