### ISSUE TITLE
Adding a 'showcase' to the readme

### ISSUE THREAD

**Issue by AmineIzumi** [Zhouzi/TheaterJS#55]
Maybe it would be a nice idea to add a showcase of what is powered by TheaterJS. It would allow new users to see what Theater is able to do, I guess ? Also, showcases are always inspirating :smile: !

**Comment by Zhouzi** [comment]
You're absolutely right, I've been thinking about it for a while now. I'm definitely going to add it and hope you'll provide a link to what you've done :)

**Comment by AmineIzumi** [comment]
Yeah, it’s still a work in progress, but I’ll be glad to show you what your script allowed me to do when I’ll finish it ! :D

**Comment by Zhouzi** [comment]
I've added a few items to the [showcase](https://github.com/Zhouzi/TheaterJS#showcase) and hope to retrieve some more.
