### ISSUE TITLE
Are you using TheaterJS?

### ISSUE THREAD

**Issue by Zhouzi** [Zhouzi/TheaterJS#56]
If so, please let me know and I'll be glad to add it to the [showcase](https://github.com/Zhouzi/TheaterJS#showcase) (or feel free to submit a pull request).

**Comment by felixheck** [comment]
@Zhouzi http://whotheheck.de/ :)

**Comment by Zhouzi** [comment]
Awesome thank you @felixheck 👍

**Comment by Zhouzi** [comment]
I'm closing this but feel free to ping me if you want your project to be showcased 😉
