### ISSUE TITLE
[bug]theater.replay not working anymore as of 2.2.0

### ISSUE THREAD

**Issue by AmineIzumi** [Zhouzi/TheaterJS#57]
Well, the title is pretty clear. Since 2.2.0, a replay call in a Scene can't trigger the "Sequence:end" event, and shows that there is no name for that Scene. **(Unable to get property 'name' of undefined or null reference**
Open the console, and look at this [fiddle ](https://jsfiddle.net/AmineIzumi/ujax42wL/) where the bug is easily reproducible - Just wait for the replay scene to start :)

**Comment by Zhouzi** [comment]
Thanks for the heads up, it was due to the way `.replay()` works and is now fixed per 4c0b752a96740983ff7c6896f151e414284cebc5 which is included in v2.2.1's release.

**Comment by AmineIzumi** [comment]
You're welcome !
Mh, another thing, when does the sequence:end event get fired ? Actually, if I "theater.stop()" when a sequence:end event is set like that for example :
`         .on('sequence:end', function () {
              theater.stop();
//Do something
              setTimeout(1400,theater.play());
          });`
since "theater.stop()" wait for the end of the sequence to stop, and that the end of the sequence play it again, it's getting somewhat complicated XD .
I guess something like that can't be fixed without editing the core mechanics of that event, so I'd like to know how to get the "state" of the current scene, to do a simple "if stopped" check before running the sequence:end function :)

**Comment by Zhouzi** [comment]
Actually the `sequence:end` event is emitted when it ends so calling `theater.stop()` in a callback that listens for it won't prevent the sequence from ending but the next scene to play. But I'm not really sure to understand what you're trying to do, would you mind providing an example?

**Comment by AmineIzumi** [comment]
Sorry, It's a bit difficult to explain something in a language other than my native one.
I wouldn't mind at all, here's [another fiddle ](https://jsfiddle.net/AmineIzumi/ce376rva/)
I figured out some things, so my question doesn't involve the sequence:end event anymore, but I'm still searching how to get the state of the scene, you'll understand with the fiddle :)

**Comment by Zhouzi** [comment]
You are looking for `theater.status` which can be:

* `ready`: nothing special is happening, the scenario is ready to be played
* `stopping`: the scenario is about to stop
* `playing`: the scenario is playing

So in your case, you could ensure that `theater.status === 'ready'`:

```
if (theater.status === 'ready') {
  // welcome user
}
```
