### ISSUE TITLE
What js files need to be imported？

### ISSUE THREAD

**Issue by zhupengGitHub** [Zhouzi/TheaterJS#60]
why I imported theater.min.js and use var theater = new Theater() cause an error no constructor Theater()

**Comment by AmineIzumi** [comment]
Have you read the [documentation ](https://github.com/Zhouzi/TheaterJS#documentation)?

**Comment by Zhouzi** [comment]
What version of TheaterJS are you using? As of v2.0.0, a TheaterJS instance must be created like so:

```javascript
var theater = theaterJS();
```

`new TheaterJS()` is deprecated and related to versions prior to 2.0.0.
