### ISSUE TITLE
Differentiation between erase and type speeds

### ISSUE THREAD

**Issue by happyventures** [Zhouzi/TheaterJS#65]
I am trying the following options
`theater = theaterJS({
  "minSpeed": {
    "erase": 80,
    "type": 450
  },

  "maxSpeed": {
    "erase": 80,
    "type": 450
  }
});`
However I am unable to have a different speed between type and erase

**Comment by Zhouzi** [comment]
The code you shared looks good, the issue may due to something else. Have a look at this [jsfiddle](https://jsfiddle.net/zv1vdmng/) and let me know if you're still having any issues. If you do, please attach the whole code.

**Comment by Zhouzi** [comment]
I guess you figured it out so I'll close the issue. Do not hesitate to get in touch if you're still having trouble.
