### ISSUE TITLE
Unable to use theater js in Angular 2+

### ISSUE THREAD

**Issue by tobieeniafe** [Zhouzi/TheaterJS#70]
I installed theaterjs via npm and added it to my typing file like any other javascript library. But whenever i add it to my component, I get an error. PS the code works fine in `.html` files.
![screenshot 227](https://user-images.githubusercontent.com/18620774/39240402-936a9f8c-487b-11e8-845d-e27d671b9a1e.png)
![screenshot 228](https://user-images.githubusercontent.com/18620774/39240403-93ab5928-487b-11e8-9625-fb95dcdad0cd.png)
![screenshot 229](https://user-images.githubusercontent.com/18620774/39240404-93fb390c-487b-11e8-9109-a025db6a633c.png)

**Comment by Zhouzi** [comment]
I am not too familiar with Angular's DOM manipulation and lifecycle but this error means the `<div id="vader">` element is not in the page when the scenario starts. Perhaps `ngOnInit` is what you need to use: https://angular.io/guide/lifecycle-hooks#oninit

**Comment by Zhouzi** [comment]
I'm closing this as the issue doesn't come from TheaterJS itself. Note that you can implement a custom "updater" thanks to the actor's callback, see: https://github.com/Zhouzi/TheaterJS#addactor
