### ISSUE TITLE
A tool that mimicks system tools automatically  ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [Zhouzi/TheaterJS#79]
Like lets say it's the wifi manager of an android phone 
And we want to mimicry it to use in a phishing captive portal page  for pentesting  
Is there a way to do make it even half automatic?  
Cause every phone has a different wifi manager !

What do you think  ?

**Comment by zhouzi** [comment]
TheaterJS is a JavaScript typing animation library, I'm afraid that's quite far from what you are looking for but correct me if I'm wrong :wink:

**Comment by minanagehsalalma** [comment]
> TheaterJS is a JavaScript typing animation library, I'm afraid that's quite far from what you are looking for but correct me if I'm wrong

I know ... I just need any kind of keywords related to my question so I can do a better search on it ...
Any suggestions are appreciated 
@Zhouzi  thanks in advance

**Comment by zhouzi** [comment]
You would like to emulate smartphones' wifi connection? I guess you could look for emulators but I doubt it's going to emulate that kind of feature. Perhaps it's all based on a few protocols. I know little to nothing about the subject though. I'm just throwing things out of thin air here, I'm afraid I can't help much. Good luck!

**Comment by minanagehsalalma** [comment]
> You would like to emulate smartphones' wifi connection? I

**Comment by minanagehsalalma** [comment]
> You would like to emulate smartphones' wifi connection?

Not exactly ... Just the WiFi selection page .... As a phishing attack page to trick the users into thinking that they Are using their real WiFi connection page to enter their password without actually functions or any thing just a fake dump page of it that all what it functions in it is the submit button 
@Zhouzi

**Comment by minanagehsalalma** [comment]
@Zhouzi just like this.... using HTML&js&css 
![IMG_20200202_223910](https://user-images.githubusercontent.com/20546638/73615510-29ece200-4611-11ea-94b4-160c344bc150.png)
![IMG_20200202_223832](https://user-images.githubusercontent.com/20546638/73615522-4721b080-4611-11ea-9973-db88ec551b2f.png)
