### ISSUE TITLE
Yippee I'm star 1000

### ISSUE THREAD

**Issue by Penderis** [Zhouzi/TheaterJS#9]

**Comment by Zhouzi** [comment]
Well, I'd like to encounter this kind of issue every day! hehe ;)

**Comment by zzz6519003** [comment]
hehe  u r chinese~

**Comment by Zhouzi** [comment]
@zzz6519003 actually I'm french but yep, my nickname is chinese as I'm a fan of chinese culture/philosophy ;)

**Comment by zzz6519003** [comment]
CURIOUS! i have recite all those words that is hard to understand when  i'm at school...
